### ISSUE TITLE
Add incompatible measures and load errors to dashboard

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio-measure-tester-gem#21]
We don't load measures with incompatible versions for testing, additionally if a measure test fails to load it is not tested.  Would be good to add this information to the dashboard, currently is only in the log file.  

https://github.com/NREL/OpenStudio-measure-tester-gem/commit/90217b72b985393554f46011ebb214e9fc9bbaef

**Comment by DavidGoldwasser** [comment]
dashboard contains this now.
