### ISSUE TITLE
There is both a syntax and structure error for missing 'description' and 'modeler description'

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio-measure-tester-gem#3]
Seems like it should just show in one of the two places.

<img width="1071" alt="screen shot 2018-02-27 at 6 29 35 pm" src="https://user-images.githubusercontent.com/4857055/36803713-a0e9406e-1c75-11e8-9889-184375142648.png">

**Comment by nllong** [comment]
Good catch. I just removed the syntax errors. Run `bundle update` on measure repos.

https://github.com/NREL/OpenStudio-measure-tester-gem/commit/b2945313c976877fa052f1bdec2be9d795b6b1c3
