### ISSUE TITLE
simplecov 1.18.2 is out, might as well update

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio-measure-tester-gem#39]
https://github.com/NREL/OpenStudio-measure-tester-gem/blob/e320b502f857ec46f9b66a02a9f0321798d411f5/openstudio_measure_tester.gemspec#L44

This really comes down to the fact that I bumped into an issue of a failing CLITest in NREL/OpenStudio here: 

https://github.com/NREL/OpenStudio/blob/04b65b87ef42bab80ff17386d68edebc50248cf4/src/cli/test/bundle_git/Gemfile#L7

I end up with a problem:

```
2716: Bundler could not find compatible versions for gem "simplecov":
2716:   In Gemfile:
2716:     simplecov
2716: 
2716:     openstudio-extension was resolved to 0.2.0, which depends on
2716:       openstudio_measure_tester (~> 0.2.0) was resolved to 0.2.0, which depends on
2716:         simplecov (= 0.18.1)
2716: F
```

So I proceeded to update NREL/simplecov and realized it was out (in https://github.com/NREL/simplecov/pull/1, I then did https://github.com/NREL/simplecov/pull/2 in the meantime)

**Comment by nllong** [comment]
I don’t think we want to point to the NREL for anymore.

- nick

Il giorno 20 feb 2020, alle ore 05:26, Julien Marrec <notifications@github.com> ha scritto:

﻿

https://github.com/NREL/OpenStudio-measure-tester-gem/blob/e320b502f857ec46f9b66a02a9f0321798d411f5/openstudio_measure_tester.gemspec#L44

This really comes down to the fact that I bumped into an issue of a failing CLITest in NREL/OpenStudio here:

https://github.com/NREL/OpenStudio/blob/04b65b87ef42bab80ff17386d68edebc50248cf4/src/cli/test/bundle_git/Gemfile#L7

I end up with a problem:

2716: Bundler could not find compatible versions for gem "simplecov":
2716:   In Gemfile:
2716:     simplecov
2716:
2716:     openstudio-extension was resolved to 0.2.0, which depends on
2716:       openstudio_measure_tester (~> 0.2.0) was resolved to 0.2.0, which depends on
2716:         simplecov (= 0.18.1)
2716: F


So I proceeded to update NREL/simplecov

**Comment by jmarrec** [comment]
@nllong yeah I don't think that we do need NREL/simplecov anymore, it's just used in a test that checks if we can install bundle stuff from github. Perhaps that test could be updated to remove this altogether.

I'm just saying that there's a new version of the official simplecov out that we might as well use since it came out like a day after you bumped it.

**Comment by nllong** [comment]
ah, so we should use 0.18.1 in the measure tester... 

I'm guessing we should update the test to use something other than simplecov

**Comment by jmarrec** [comment]
I mean just change:

https://github.com/NREL/OpenStudio-measure-tester-gem/blob/e320b502f857ec46f9b66a02a9f0321798d411f5/openstudio_measure_tester.gemspec#L44

Replace with 1.18.2.
