### ISSUE TITLE
Some measures pass tests when run on single measure directory but fail when run from nrel_published

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio-measure-tester-gem#4]
The following measures pass all of their unit tests if I call `rake openstudio:test` from within the individual measure but fail if I run them from "nrel_published" I'm not sure of the cause. Some of these are reporting measures, others are not.

 - [ ] AedgK12ExteriorLighting
 - [ ] Meter Flood Plot
 - [ ] Generic QAQC
 - [ ] OpenStudio Results
 - [ ] HVACPsychrometricChart
 - [ ] GLHEProExportLoadsForGroundHeatExchangerSizing

Most of these are reporting measures and the issue is finding time series SQL results, but the Exterior Lighting and GLHEPro are not. It is a bit odd that the test isn't repeatable in a single test vs. test of set of measures, any thoughts one what is different about how they are run?

**Comment by nllong** [comment]
Try running `bundle update` and then the tests again. I deleted a bunch of the measures except for a couple of the above ones (and some other random ones) and they seemed to run. I'm worried that there is something in one of the other measures that is stepping on something more global.

![screen shot 2018-03-06 at 8 38 39 am](https://user-images.githubusercontent.com/1907354/37041705-105b4c32-211a-11e8-91df-1e99ea9b6b31.png)
