### ISSUE TITLE
minor readme update needed for ruby version

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio-measure-tester-gem#41]
https://github.com/nrel/OpenStudio-measure-tester-gem#testing-in-docker

mentions ruby 2.2.4

**Comment by jmarrec** [comment]
Not sure it'll actually work with `install_ruby.sh 2.5.5`

https://github.com/NREL/OpenStudio-server/blob/d763df8dc9e05f98960e0eb82e843a9145edc44b/docker/deployment/scripts/install_ruby.sh#L10

**Comment by nllong** [comment]
ugh, yeah, I'll need to update that script too... fun stuff, i tell ya.
