### ISSUE TITLE
Support PV as valid upcase class name

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio-measure-tester-gem#5]
If we don't do this then I'll change the measure, but I thought we decided to add that to the list of acceptable measures.

Well, I see that currently there are two PV measures, and one of them uses "PV" while another uses "Pv" so whichever way we choose, I'll fix one measure or the other.

**Comment by DavidGoldwasser** [comment]
@nllong I'll wait to see what your preference is on this before doing anything.

**Comment by nllong** [comment]
upcased PV is the convention https://github.com/NREL/OpenStudio-measure-tester-gem/blob/master/lib/openstudio_measure_tester/core_ext.rb#L51
