### ISSUE TITLE
pin parser dependency

### ISSUE THREAD

**Issue by kflemin** [NREL/OpenStudio-measure-tester-gem#66]
the parser dependency, required by rubocop, has a new dependency named 'racc'. this has native extensions and is breaking the openstudio bundler workflow.  Pinning the parser dependency to 3.2.2.2 fixes this issue.

**Comment by jmarrec** [comment]
@kflemin I just came to the same conclusion, cf https://github.com/NREL/OpenStudio/issues/5091

Could you release a new version with this PR/Commit.?

**Comment by kflemin** [comment]
@jmarrec done!

**Comment by jmarrec** [comment]
Thank you @kflemin . Seems like I still run into trouble trying to consume other gems that depend on things that transitevely require racc (like rubyXL or Nokogiri) but that's one less thing to worry about.

We'll probably need to figure out what's the matter with racc...

**Comment by kflemin** [comment]
maybe it needs to get added here since it now has a native extension dependency: https://github.com/NREL/openstudio-gems/blob/develop/Gemfile#L24 ?

**Comment by jmarrec** [comment]
Duh. Of course that's the issue, I don't know how I missed it. Thanks a ton @kflemin! I'll need to do that and init it properly in the CLI.
